### PR TITLE
Relicense as dual APACHE/MIT

### LINKED ISSUE #47: Re-license as dual Apache/MIT
Re-license as dual Apache/MIT which is common in the greater Rust ecosystem.

### PR DESCRIPTION
**Pull request by grovesNL**
Fixes #47.

@kvark and @msiglreith please confirm if you're okay with relicensing your contributions.

### CODE REVIEW

**Comment by kvark** [comment]
Yes I'm ok with this.

**Comment by grovesNL** [comment]
Thanks! bors r+

**Comment by grovesNL** [comment]
Thanks! bors r=kvark

**Comment by grovesNL** [comment]
Forgot a newline
bors r=kvark

**Pull request merged**
