### PR TITLE
Expose SPIRType::ImageType to Rust

### PR DESCRIPTION
**Pull request by Rob2309**
These changes allow querying the type of an Image/SampledImage resource more effectively. Now you can query
- The dimension of the Image (1D, 2D, Cube, etc.)
- The format of the Image, if known
- How it is accessed (Sampled or read directly)
- whether it is an array texture
- ...

### CODE REVIEW

**Review by grovesNL — APPROVED** [review]
Great, thanks!
bors r+

**Comment by grovesNL** [comment]
bors retry

**Comment by Rob2309** [comment]
Oh I forgot to mention, I also exposed the array_size_literal information for the types it applies to. "storage" and "width" fields are also present in the wrapper but not yet exposed to rust, since I had no need for them yet.

**Comment by grovesNL** [comment]
Sounds good :+1: thanks!

**Pull request merged**
