### PR TITLE
Support Linux/clang

### PR DESCRIPTION
**Pull request by grovesNL**
Improve macos/Clang detection with newest cc-rs commits (waiting for a new cc-rs crate to be published) and add more variations to Travis.

### CODE REVIEW

**Comment by grovesNL** [comment]
Should fix #33.

@GabrielMajeri could you test this branch before I merge?

**Comment by GabrielMajeri** [comment]
@grovesNL it works!

**Comment by grovesNL** [comment]
@GabrielMajeri Great, thanks for testing!

**Comment by grovesNL** [comment]
Not sure what happened with codecov here, I think it needs some more work.

bors r+

**Pull request merged**
