### PR TITLE
Update bindgen #102

### PR DESCRIPTION
**Pull request by metaphorshear**
Just updated bindgen in the bindings_generator folder and fixed some deprecated things.  Did wasm_bindgen need to be updated?

### CODE REVIEW

**Comment by metaphorshear** [comment]
Thanks!

I've figured out how to squash my commits locally.  Should I push that out?
I've tried running `cargo build`, but I don't have libclang, so I didn't get very far.  I can set it up tomorrow and let you know.

**Comment by grovesNL** [comment]
Sure, you can force push the squashed commit to this branch (i.e. `git push origin update-bindgen --force`). Sounds good!

**Comment by kvark** [comment]
fwiw, I do `git push -f origin HEAD` (which does the same in our case)

**Comment by metaphorshear** [comment]
When I try to run `cargo run --bin bindings_generator` from the root directory, I get this error:
`error: error reading '/root/spirv_cross/../spirv_cross/src/wrapper.hpp'`
`thread 'main' panicked at 'TranslationUnit::parse failed', src/libcore/option.rs:1190:5`
So, I haven't been able to generate bindings.  I can't figure out why it's putting the `..` in there.

**Comment by grovesNL** [comment]
Oh ok, it relies on the current directory being `bindings_generator` (we could probably improve that). So I don't run it from the root directory, I just `cd` into `bindings_generator` and use `cargo run`

**Comment by metaphorshear** [comment]
Okay, before I was getting an error from running `cargo run` in the `bindings_generator` directory, but I tried it today and it generated bindings.  Do you want me to attach the files?

**Comment by grovesNL** [comment]
@metaphorshear sorry, I didn't see your message until now. It would be great if you could commit the files in this PR, otherwise we can merge it as is and I can update it later :+1:

**Comment by metaphorshear** [comment]
Okay, I committed the files

**Comment by grovesNL** [comment]
Thanks again! Merged in #129

**Pull request closed without merging**
